title: READIxTSAR @ LREC 2026
page-top-title: READIxTSAR @ LREC 2026
top-section-bg-text: READIxTSAR
home-subtitle: Joint Workshop on Readability and Text Simplification
copyright-text: "READIxTSAR Organizers 2025."
